use role ACCOUNTADMIN;    -- change this
use DATABASE DEV_DB;      -- change this
use schema SCRATCH;       -- change this

CREATE STORAGE INTEGRATION AWS_SNOWFLAKE_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<AWS_ACCOUNT>:role/<ROLE_NAME>' -- change this
  STORAGE_ALLOWED_LOCATIONS = ('s3://<AWS_S3_BUCKET>/users/');  -- change this

DESC INTEGRATION AWS_SNOWFLAKE_INTEGRATION;

CREATE STAGE S3_STORAGE_STAGE
  STORAGE_INTEGRATION = AWS_SNOWFLAKE_INTEGRATION
  URL = 's3://<AWS_S3_BUCKET>/users/'      -- change this
  FILE_FORMAT = (TYPE = JSON COMPRESSION = NONE);

